site_name: GitFleet Documentation
docs_dir: docs
site_dir: site

plugins:
  - awesome-pages


theme:
  name: material
  palette:
    - scheme: default # Light mode
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark
    - scheme: slate # Dark mode
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light

    - features:
        - navigation.tabs # Top tabs
        - navigation.expand # Expand sections
        - search.highlight # Highlight search terms
        - toc: false # Left side bar
        - content.code.annotate
      vars:
        content-width: 90%

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
