name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout

      - uses: ./.github/actions/setup-python
        with:
          python-version: "3.12"

      - uses: ./.github/actions/rust-toolchain

      - name: Cache pip
        uses: ./.github/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install maturin pytest
          pip install -e ".[dev]"

      - name: Build Rust extension with maturin
        run: |
          source .venv/bin/activate
          maturin develop

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
