name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout

      - uses: ./.github/actions/setup-python
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: ./.github/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('**/mkdocs.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install documentation dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin

      - name: Build docs
        run: mkdocs build

      - name: Deploy to gh-pages/docs
        uses: ./.github/actions/gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          destination_dir: docs
          keep_files: true
