name: Model Validation

on:
  push:
    branches: [main]
    paths:
      - 'GitFleet/models/**'
      - 'GitFleet/providers/**'
      - 'tests/test_github_models.py'
  pull_request:
    branches: [main]
    paths:
      - 'GitFleet/models/**'
      - 'GitFleet/providers/**'
      - 'tests/test_github_models.py'
  # Enable manual triggering
  workflow_dispatch:

jobs:
  validate-models:
    runs-on: ubuntu-latest
    name: Validate Pydantic Models
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio python-dotenv maturin
          pip install -e ".[dev,pydantic]"
          
      - name: Build Rust extension
        run: |
          maturin develop
      
      - name: Run model validation tests
        run: |
          pytest tests/test_github_models.py -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}